language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sudo apt-add-repository -y ppa:linuxjedi/ppa
  - sudo apt-get update -qq
  - sudo apt-get -y install libuv-dev
  - phpize && ./configure --with-uv --enable-httpparser && make && sudo make install
  - echo "extension=uv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#php-uv"
    skip_join: true
    use_notice: true 
