language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - REPORT_EXIT_STATUS=1

before_install:
  - chmod +x travis-install.sh

install: ./travis-install.sh

script:
  - php run-tests.php -p `which php` --offline --show-diff --set-timeout 120

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#php-uv"
    skip_join: true
    use_notice: true 
