name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.3
#           - 8.2
#           - 8.1
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpize, pecl, php-config
      - name: install deps
        run: sudo apt-get install -y ninja-build ccache pkg-config libasan8 libubsan1 build-essential valgrind >> /dev/null
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.24'
      - name: 'Install Libuv'
        run: sudo ./scripts/compile-libuv.sh RelWithInfo v1.48.0 >> /dev/null
      - name: Compile uv extension
        run: phpize && ./configure && sudo make install && echo "extension = uv" >> $(php -r 'echo php_ini_loaded_file();')
      - name: Run the tests
        run: php run-tests.php -q -j4 -p $(which php) --offline --show-diff --set-timeout 120
